.travis.yml

See http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/ for related documentation.
This makes builds faster.

travis: Use docker infrastructure

---

.rultor.yml

This allows merging via github comments. The comment `@rultor merge`
will execute the script (which currently doesn't do anything) and if it
succeeds will perform the merge.
I plan to use rultor later for:
* Automatic deployment to PyPI (development releases directly from
master, we do this already in coala, see
https://github.com/coala-analyzer/coala/blob/master/.rultor.yml)
* Automatic releasing with deployment to PyPI.
* Veryfy that all CI services pass before merging (see
https://github.com/yegor256/rultor/issues/869)
With this any manual pushes to master are disallowed, all pushes to
master have to be validated by continuous integration and reviewed by a
non-committer.

Add rultor configuration

---

docs/dates.rst
docs/locale.rst

Docs: minor fixes

---

CHANGES
babel/__init__.py
babel/numbers.py
scripts/import_cldr.py
setup.py
tests/test_core.py

This pull request is intended to backport the changes made by @jun66j5 to fix #174, please, refer to the original issue for more information:
- https://github.com/mitsuhiko/babel/issues/174
- https://github.com/mitsuhiko/babel/pull/188

Backporting #174 bugfix to 2.x version

---

babel/util.py
tests/test_util.py

FixedOffsetTimezone: fix display of negative offsets

---

babel/util.py
tests/test_util.py

Backport: FixedOffsetTimezone: fix display of negative offsets

---

README
docs/_templates/sidebar-links.html
docs/conf.py
docs/installation.rst

docs: Change repository adress

---

setup.cfg

@etanol want to review this one?

[MAINTENANCE BACKPORT] setup.cfg: Use universal wheel

---

setup.cfg

setup.cfg: Use universal wheel

---

CHANGES

This PR just adds entries to the `CHANGES` file in order to prepare the `2.1` release.

2.1 release preparation

---

setup.py

for issue #260. I am new to python so please let me know if I did not do this correctly.

Change to using include_package_data

---

.ci/appveyor.yml
.travis.yml
setup.py

Mark Python 3.5 as supported

---

babel/core.py
tests/test_core.py

Add hash to locale class

---

babel/messages/catalog.py
tests/messages/test_catalog.py

Rebased version of #54 with added test.
Closes #54.

Update catalog headers from the template

---

babel/messages/plurals.py
tests/messages/test_plurals.py

Rebased version of #116.
Closes #116.

Fix typo and add missing semicolon in plural_forms, update test coverage.

---

CONTRIBUTING.md

Fixes https://github.com/python-babel/babel/issues/345

Contributing:Change incorrect link

---

docs/license.rst

license.rst: Fix minor typo error

---

babel/core.py

Changed win_mapping to windows_zone_mapping in core.py line 48

Issue #463. 

---

babel/dates.py
tests/test_dates.py

Thanks to @stringtheory for the bug report!
Fixes #428

Properly fall back to `long` metazone names when short forms are no-inherit

---

babel/core.py
babel/numbers.py
babel/units.py
scripts/download_import_cldr.py
scripts/import_cldr.py
tests/test_core.py
tests/test_date_intervals.py
tests/test_dates.py
tests/test_languages.py
tests/test_lists.py
tests/test_numbers.py

Upgrade to CLDR 31

---

scripts/import_cldr.py

Thanks @kedarkhetia and @patricknaughton01 for their patches for the issue :)
Fixes #397
Closes #483 
Closes #556

Ignore currency symbol alt forms

---

.ci/appveyor.yml
.ci/run_with_env.cmd
CONTRIBUTING.md
babel/dates.py
babel/languages.py
babel/numbers.py
babel/plural.py
babel/support.py
babel/units.py
docs/_templates/sidebar-links.html
docs/conf.py
docs/dates.rst
docs/installation.rst
docs/intro.rst
docs/locale.rst
docs/messages.rst
docs/numbers.rst
scripts/import_cldr.py

Updated docs and code comments.

Use https URLs throughout project where available

---

docs/messages.rst

since this will work on python3

switch print statement in docs to print function

---

babel/numbers.py
babel/units.py
scripts/download_import_cldr.py
tests/test_numbers.py

Download CLDR 34.0

---

scripts/import_cldr.py
tests/test_dates.py

CLDR: Skip alt=... for week data

---

.travis.yml

Travis: test on Python 3.8-dev

---

babel/core.py
tests/test_core.py

get_display_name(): Don't attempt to concatenate variant information to None

---

.gitignore
babel/messages/frontend.py
tests/messages/data/project/i18n/fi_BUGGY/LC_MESSAGES/messages.po
tests/messages/test_frontend.py

pybabel compile: exit with code 1 if errors were encountered

---

docs/installation.rst

Add install of pytz before import_cldr

---

scripts/import_cldr.py

As [Miro Hrončok pointed out](https://github.com/python-babel/babel/pull/710#discussion_r419738390) we don't need ".iter()" in the script.

simplify iteration code in "import_cldr.py"

---

.github/workflows/test.yml

CI: update OS versions + PyPy baseline to 3.7

---

babel/messages/frontend.py

Fix import statement in messages/frontend.py

---

babel/core.py
babel/dates.py
babel/lists.py
babel/localedata.py
babel/localtime/_win32.py
babel/messages/catalog.py
babel/messages/checkers.py
babel/messages/extract.py
babel/messages/frontend.py
babel/messages/pofile.py
babel/numbers.py
babel/plural.py
babel/support.py
babel/units.py
babel/util.py
scripts/generate_authors.py
scripts/import_cldr.py
setup.py
tests/messages/test_catalog.py
tests/messages/test_frontend.py
tests/messages/test_pofile.py
tests/test_core.py
tests/test_plural.py
tests/test_support.py

Original conversion suggestions via flynt, edited by hand.

Replace %/.format/concatenation with f-strings where feasible

---

babel/dates.py
babel/numbers.py
babel/units.py
scripts/download_import_cldr.py
tests/test_numbers.py
tests/test_support.py

Use CLDR 44

---

MANIFEST.in
babel/locale-data/LICENSE.unicode
docs/license.rst

Include Unicode license in `locale-data` and in documentation

---

tests/test_numbers.py

Line 55 in test_numbers.py appeared to be a duplicate of the line before it 
Fixes #1025.

"Deleted duplicate code in test"

---

docs/conf.py

Adjust docs/conf.py to add compatibility with sphinx 8
