python-babel/babel

.gitignore

.idea stores settings for PyCharm, ~ files are temporary files e.g. used
by gedit. .swp is used by vim. We don't want any of those to be
accidentally committed in the repo.

gitignore: Add temporary editor files

---

docs/setup.rst

Now the setup.cfg example for extract_messages configuration is equivalent to the command line example.

Fix typo on mapping filename

---

babel/support.py
tests/test_support.py

When copy.copy or copy.deepcopy is used to copy LazyProxy, __init__ is never called and self._value is never set to None. Accessing it in self.value (which is used in __getattr__) triggers another call to __getattr__, resulting in endless recursion.

Add __copy__ and __deepcopy__ to LazyProxy.

---

babel/localedata/__init__.py
babel/numbers.py
scripts/import_cldr.py
tests/test_numbers.py

The method to generate the name for the parent locale has some exceptions. Notably the latin america regions (es_MX, es_CO, es_AR, etc...) which should inherit from es_419 instead of es. Fortunately, these exceptions are described in the element of the supplemental data document.
This pull request tries to implement the proper locale inheritance for such cases.
~~There is an ugly hack because one of the commits introduces a circular dependency between `babel.core` and `babel.locale`.~~
**NOTE:** This is a new pull request that should supersede #117 and fix #97.

Last attempt to support parent locale exceptions

---

.ci/appveyor.yml
.ci/deploy.linux.sh
.ci/deploy.osx.sh
.ci/deps.linux.sh
.ci/deps.osx.sh
.ci/run_with_env.cmd
.gitignore
.rultor.yml
.travis.yml
Makefile

This pull request adds near the same CI settings found at the `master` branch. The only difference is that I removed any Python 3.4 related settings. Official 3.4 support was added (and I think it should remain) in the upcoming 3.0 release.

Backport CI settings to 2.x

---

babel/numbers.py
scripts/import_cldr.py
tests/test_core.py

Proposed changes for #174.
In Babel 2.0, `*.dat` files use `datetime.date` class. However, pickle data format for the `date` class is incompatible between Python 2 and 3. Proposed changes remove uses of `date` class from `*.dat` files and add check for only `babel.*` classes in `*.dat` files.

Avoid incompatible *.dat files between Python 2 and 3

---

CHANGES
babel/util.py

Odict setitem method is linearly searching if item is present in keys list, which significantly reduces performance on big dict. Make it use hash.

Improve odict performance by making key search O(1)

---

babel/dates.py
tests/test_dates.py

e.g.
```python
>>> format_timedelta(timedelta(hours=3), format='short', locale='en')
u'3 hrs'
>>> format_timedelta(timedelta(hours=3), format='narrow', locale='en')
u'3h'
>>> print format_timedelta(timedelta(hours=3), format='short', locale='gu_IN')
3 કલાક
>>> print format_timedelta(timedelta(hours=3), format='narrow', locale='gu_IN')
3 ક
```

Add format_timedelta(format='narrow') support

---

babel/util.py
tests/test_util.py

`odict.pop` method does not remove the key from the `_keys` attribute if
the default argument is not specified.

Fix odict's pop method

---

babel/util.py

It looks like this dates back all the way to 2007,
and the initial import of the code in commit 00f16f9.
Since Python 2.6 is the minimum supported version, and that has
os.path.relpath this is no longer needed.

Remove unneeded relpath() polyfill

---

CHANGES

This was introduced in
https://github.com/moreati/babel/commit/edc5eb57b2f7c36bb419be4d23396746d233767b
and forgotten to add to CHANGES.

CHANGES: Add "narrow" support for format_timedelta

---

README
docs/_templates/sidebar-links.html
docs/conf.py
docs/installation.rst

The repository moved.
Backport version of https://github.com/python-babel/babel/pull/231

BACKPORT: docs: Change repository adress

---

setup.py

Print error message and exit if Python version requirement not satisfied.

Enforce Python version in `setup.py`

---

.rultor.yml

Something's wrong here and we do need to debug that first. So in order
for us  being able to do rultor merges, let's just not execute tests for
now.
@etanol @erickwilder could you please review and merge this before others as this blocks all rultor based merges?

rultor: Remove test execution

---

CHANGES

We recently changed branching and this was missing from
43638b27a0a2abf71d636c8c16c1ce0b3c010cc4

CHANGES: Make 2.2 next version

---

CHANGES
babel/numbers.py
scripts/import_cldr.py
tests/test_numbers.py

This extends pull request #117 to also load the currency fraction information from CLDR supplemental data. Once loaded, it adds an option to babel.numbers.format_currency so the decimal positions deduced from the format pattern can be ignored and replaced by those of the currency, as indicated by such supplemental information.
The API remains backwards compatible.

Use currency fraction information

---

AUTHORS
CHANGES
babel/core.py
babel/numbers.py
scripts/import_cldr.py
tests/test_core.py
tests/test_numbers.py

In order to fix #201, it was necessary to properly interpret the `type` attribute of the `currencyFormat` elements in CLDR data.  It apparently changed between version 23 and 26.

Fix the loading of the currency format types

---

docs/dates.rst

Update example in Date and Time documentation to reflect metazone translation.
Fixes https://github.com/python-babel/babel/issues/108

documentation: Correct timezone in example.

---

babel/core.py
babel/lists.py
scripts/import_cldr.py
tests/test_lists.py

Adds a format_list function which formats a python list according to the locale e.g. ['a', 'b', 'c'] will be formatted as "a, b and c" in english or "a、b和c" in chinese.

Add a format_list function

---

babel/messages/plurals.py
tests/messages/test_plurals.py

Provide only one option for chinese in the plural data. The 3 previous options were all the same and I've checked with a chinese colleague she thinks that applies to all variants on the chinese language. 
Before this change things like ```get_plurals('zh_CN')``` would return the default plural rules because that string would get expanded out to ```Locale('zh', 'CN', 'Hans')``` with string representation ```"zh_Hans_CH"```, which isn't in the table. 
I feel like this is side stepping the underlying issue that the way that this table is searched isn't very flexible, but I thought it might be a pragmatic improvement.

Fix zh plural selection

---

.travis.yml
babel/_compat.py
babel/numbers.py
babel/plural.py
tests/test_numbers.py
tests/test_plural.py
tox.ini

At work, we had some performance issues when trying to format almost 100,000 prices in a single report.  Some profiling revelaed inefficiencies in the number rounding functions.  Such number rounding operations can be implemented making use of the `decimal` standard Python module.  Which probably means that the number rounding code in Babel was meant to support Python versions below 2.4.
Since the oldest supported version now is 2.6, it is probably time to remove the rust and make more use of the standard library (when compatibility is not an issue).
Moreover, this pull request also contains some additional code to make use of the `cdecimal` implementation when available (already shipped with Python since 3.3).  Which speeds up some operations considerably.  Here are some dumb …

Faster rounding

---

babel/messages/pofile.py
tests/messages/test_pofile.py

I'm proposing that locations without line numbers should work. Currently they are just swallowed. Other tools like msgmerge from gettext keep them as they are. Locations without line numbers are useful to reduce the number of differences when templates and code are edited without changing any of the translations.
The current implementation might break backward compatibility for other code that uses pofile from Babel.
Another possible solution would be to just keep unparsed locations as regular comments, but that is quite a bit more complex to handle correctly in my opinion.

Allow file locations without line numbers.

---

babel/messages/extract.py
tests/messages/test_extract.py

This makes it much easier to do create custom extraction machinery without having to bother with external configuration files or Setuptools entry points.

Allow passing a callable to `extract()`

---

babel/core.py
scripts/import_cldr.py

This exposes the rules for selecting ordinal forms in a similar way to the rules for selecting plural forms. In general a languages plural forms and ordinal forms might not be related. 
I was hoping to provide a format_ordinal function to do conversions like 1->1st, 2->2nd, 11->11th, 23->23rd etc. unfortunately the CLDR doesn't have any convenient data for this. It does have some in the rbnf data but the language coverage at least in CLDR 26 seems patchy and pretty hard to interpret.
But I think this is useful on it's own because it provides access to the ordinal rules so that you could construct a simplified solution to a reduced problem based on these rules. Indeed that is what I'm doing for the small set of locales that I need to support.

Add an ordinal_form property to Locale

---

.travis.yml
tox.ini

The cdecimal extension doesn't seem to install anymore.  It looks like it has been renamed to m3-cdecimal.  However, in my system doesn't install properly either.  Let's try Travis to see if it has better luck.

Try to fix the broken builds

---

babel/support.py
tests/test_support.py

`filter` is special in Python 3, and latter usages would error out in
strange ways.
Fixes #92
Fixes #162

Flatten NullTranslations.files into a list

---

.gitignore
babel/core.py
babel/dates.py
babel/numbers.py
scripts/download_import_cldr.py
scripts/import_cldr.py
tests/messages/test_plurals.py
tests/test_dates.py
tests/test_numbers.py
tests/test_plural.py

This PR:
* Updates Babel to use CLDR 28, including some fixes for new CLDR features.
* Includes some development convenience switches for the CLDR import scripts
I'd love to have more behavioral tests that ensure there aren't serious regressions in behavior (for example by way of mis-parsing the XML files), but I'm not quite sure where to source the data for that for several languages. For the time, the current tests will have to do.
It would also be a great idea to compare and contrast the parser behavior to the actual spec (http://www.unicode.org/reports/tr35/tr35-39/tr35.html#Modifications and previous versions as linked therein).

Upgrade to CLDR 28

---

babel/util.py
tests/test_util.py

If the first line of a python file is not a valid latin-1 string,
parse_encoding dies with "UnicodeDecodeError". These strings nonetheless can be
valid in some scenarios (for example, Mako extractor uses
babel.messages.extract.extract_python), and it makes more sense to ignore this
exception and return None.

Fix UnicodeEncodeError on file encoding detection

---

babel/core.py
babel/dates.py
scripts/import_cldr.py
tests/test_core.py
tests/test_dates.py

The skeletons for dates and times are described on
http://cldr.unicode.org/translation/date-time-patterns under
Additional Date-Time Formats. And are useful when you want to some more
control over formatting dates and times but don't want to force all
locales to use the same pattern.

Add support for date-time skeletons

---

.gitignore
babel/messages/frontend.py
tests/messages/test_frontend.py

This PR is directly inspired by #62.
A little bit of intricate, fine magic is used to create an Optparse parser out of the Distutils commands, a little bit of fine-tuning here and there and then everything . . . just works, with a third less code.
The `,fuzzy` changes in the tests are actually an oversight that this PR fixes as a side effect: The commit e85e71d22f4ef6c8f117cbe2d16758b20125cc0d had added `catalog.fuzzy = False` to the distutils command code, but the same change had never made it into the CLI code.
This should do wonders for test coverage statistics, which also means the frontend code will be more easily maintained.

Refactor frontend.py (remove duplicate code)

---

babel/messages/catalog.py
babel/messages/frontend.py
tests/messages/test_catalog.py

The change in e0e7ef168856bb had an unexpected and likely undesired effect
when updating catalogs with, e.g. translator names in the header comment.
It's better to make the updating an option and revert back to the pre-2.2
behavior by default.
Fixes https://github.com/python-babel/babel/issues/318

Make catalog header updating an option

---

babel/core.py
babel/languages.py
docs/api/index.rst
docs/api/languages.rst
scripts/import_cldr.py
tests/test_languages.py

This PR is a rebase of and supersedes #122 and #123.

Territory languages

---

babel/messages/extract.py
babel/messages/frontend.py
tests/messages/test_frontend.py

Reason for the change: https://github.com/python-babel/babel/issues/253 . This obviates the need for parallelizing to make things faster (on the consumer's side, we only scan files that are different in a given branch compared to origin's master, which brings scan time down from ~4min 30s to ~5-20s, depending on how old one's branch is). 
Code changes: moved half of the logic from extract_from_dir into its own function. Then added a few "is this a path or directory?" type checks to frontend.py to use the right thing. Those checks are kind of ugly right now but I couldn't think of a more elegant way of doing it. Added/rejiggered a couple of tests.

Support extraction by filename as well as directory

---

babel/core.py
babel/dates.py
docs/api/dates.rst
scripts/import_cldr.py
tests/test_date_intervals.py
tests/test_dates.py

Nb: There are some plumbing commits at the top -- the changes there are required by the actual interval code.
Fixes #276

Implement date interval formatting

---

babel/messages/frontend.py
tests/messages/data/project/i18n/de_DE/LC_MESSAGES/bar.po
tests/messages/data/project/i18n/de_DE/LC_MESSAGES/foo.po
tests/messages/test_frontend.py

Some projects have their translations split up into several text
domains within one package.  This change adds the possibility to
specify a space seperated list of domains in the configuration, like
'setup.py compile_catalog --domain="foo bar"', for instance.

Frontend: Add multi-domain support to compile_catalog command

---

babel/messages/pofile.py
tests/messages/test_pofile.py

I think sorting message locations irrespective of the sort flags is alright.
The only UC I can think of where that wouldn't be desired might be trying to read a .po and emitting an identical copy of it, but I don't think Babel does that as it is anyway?

Embetter pofile sorting

---

babel/messages/frontend.py
tests/messages/test_frontend.py

Just in case some script expects to be able to pass `--input-dirs`.
Fixes #330
Augments 19957e21470615d42fb7b6e2c1a580cd679d33c8

Extract CLI: Add `input-dirs` alias for `input-paths`

---

babel/messages/extract.py
tests/messages/test_extract.py

Add the npgettext as a default keyword in the keywords map.
Create test_npgettext in test_extract showing the passing tests.
Fixes https://github.com/python-babel/babel/issues/281
Fixes https://github.com/python-babel/babel/issues/328

Extract: Add npgettext to default keywords map

---

.travis.yml
setup.py

As suspected in #250, Babel runs fine on PyPy3, it's just that `setup.py` complains. No more!
Fixes https://github.com/python-babel/babel/issues/250

Set up official support for PyPy 3

---

babel/plural.py
tests/test_plural.py

See http://www.unicode.org/reports/tr35/tr35-numbers.html#Operands
See https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html
Fixes #287

Compile noninteger TR35 operands to zeroes when emitting Gettext

---

scripts/import_cldr.py

The CLDR importer script was mostly one function of nearly 500 lines, which was frankly silly.
This PR breaks it into multiple functions that do one bit of importing before passing on the proverbial torch to another import function, et cetera. The script behaves exactly as before wrt the resulting locale data files, though!
As the commit messages say,
> Special care was taken to order the new functions in the same order as the original source was; the resulting whitespace-ignoring diff is very minimal.
So, before you are too daunted to review this, **please use `git diff -w` or the `?w=1` query parameter on GitHub:**
```shell
$ git diff --stat master
scripts/import_cldr.py | 929 +++++++++++++++++++++++++------------------------
1 file changed, 474 insertions(+), 455 deletions(-)
$ git …
```

Refactor CLDR importer script

---

tests/test_localedata.py

I just had a little doubt about the relationship between `locale_identifiers()` and `exists()`, so I made a tiny test to make sure the two refers to the same locale IDs taxonomy.

Unittest locale_identifiers() and exists() bijection.

---

docs/dates.rst

Fixes https://github.com/python-babel/babel/issues/356

docs/dates.rst: Correct line length

---

babel/dates.py
tests/test_dates.py

Fixes https://github.com/python-babel/babel/issues/350

format_datetime: using 'S...S' format is incorrect

---

babel/localedata.py
tests/test_localedata.py

Following #351, it seems that mixed-cased locale IDs are not properly checked as existing depending on the platform.
The issue lies in `babel.localedata.exists()` which rely on filesystem assets. As a result, mixed-cased locale IDs are properly parsed on OSX (case-insensitive filesystem) but not on Linux.
The first commit [demonstrate the issue](https://travis-ci.org/python-babel/babel/builds/113096167) depending on the system.
The second commit ensure that locale IDs recognized by Babel are uniques, even if lower-cased.
The third commit fix to the issue.

Parsing of mixed-cased locale ID.

---

docs/numbers.rst

Fixes https://github.com/python-babel/babel/issues/363

docs/numbers.rst: Correct line length

---

.pre-commit-config.yaml
babel/core.py
babel/messages/pofile.py
babel/numbers.py
babel/util.py
scripts/make-release.py
tests/messages/test_catalog.py
tests/test_core.py
tests/test_dates.py
tests/test_localedata.py
tox.ini

Added `flake8` and `reorder-python-imports` [pre-commit](https://github.com/pre-commit/pre-commit) [hooks](https://github.com/pre-commit/pre-commit-hooks) and applied fixes.

Add `flake8` pre-commit hook and applied fixes

---

babel/core.py
babel/dates.py
scripts/import_cldr.py
tests/test_day_periods.py

This PR adds full support for day periods other than am/pm.
Requested by @sachinpali146 for additional time format character support. :)
See: http://unicode.org/reports/tr35/tr35-dates.html#Day_Period_Rules

Day period API

---

babel/dates.py
tests/conftest.py
tests/test_dates.py
tests/test_smoke.py

See issue #378 for discussion.
We should release 2.3.2 when this fix is in, if no other bugs/regressions are found.

Fix day period formatting (#378)

---

babel/messages/frontend.py
tests/messages/test_frontend.py

This fixes #384 and includes @sebdiem 's patch from #383 (which fixes #385 too).

Fix CLI command usage regressions

---

scripts/import_cldr.py

This reverts commit 9b5c7f3678167f03ec39fd1c25f98d0e0d41621f.
Addresses https://github.com/python-babel/babel/issues/391, not much else to say. :) FYI @aronbierbaum

Revert "import_cldr: if lxml is installed, use it"

---

babel/messages/frontend.py
tests/messages/test_frontend.py

I so hope this will be the last we see of this series of bugs...
Fixes #388
Fixes #390
Refs #384
Refs #311

Re-harmonize argument parsing between distutils and optparse CLIs

---

babel/messages/jslexer.py
tests/messages/test_jslexer.py

A less greedy jsx_tag regex. Can handle both translatable strings as
children or as props to a component.
Also made a test case with the kind of JSX syntax variants we're using.

jslexer.py: Change jsx_tag regex

---

babel/messages/extract.py
tests/messages/test_extract.py

The following python3 source file:
```python3
print(_('☃'))
```
has UTF-8 encoding (by default without a pragma).  The code I touched (before my change) caused this to be scanned as latin-1 (mojibake)
The section of PEP8 which covers this: http://legacy.python.org/dev/peps/pep-0008/#source-file-encoding

Default to UTF-8 source encoding (PEP8: python3)

---

tests/test_dates.py

When running the test suite from my computer, I had the following failure:
```
====================================================== FAILURES =======================================================
_______________________________________________ test_get_timezone_name ________________________________________________
def test_get_timezone_name():
dt = time(15, 30, tzinfo=timezone('America/Los_Angeles'))
assert (dates.get_timezone_name(dt, locale='en_US') ==
u'Pacific Standard Time')
assert (dates.get_timezone_name(dt, locale='en_US', return_zone=True) ==
u'America/Los_Angeles')
assert dates.get_timezone_name(dt, width='short', locale='en_US') == u'PST'
tz = timezone('America/Los_Angeles')
assert dates.get_timezone_name(tz, locale='en_US') == u'Pacific Time'
assert …
```

Fix the way a local time is constructed in tests

---

CONTRIBUTING.md
tests/messages/test_plurals.py

As per their email ‘Changes to project subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs link for their .org -> .io migration for hosted projects

---

babel/core.py
babel/numbers.py
tests/test_core.py
tests/test_numbers.py

More precisely, `babel.numbers.parse_pattern()` only passes the positive string format to `NumberPattern()`. Fixed the method so that it now passes the entire original pattern string.

parse_pattern now preserves original pattern #407

---

babel/dates.py
scripts/download_import_cldr.py
scripts/import_cldr.py

Everything... seems to work, at least!
Fixes #404

Use CLDR 29

---

.travis.yml
babel/messages/pofile.py
tests/messages/test_pofile.py

This fixes issue #27. I also found with multi-line obsolete units it would mark the following unit as obsolete. This fixes that also. 
The fixes are entirely confined to the second commit. The first commit refactors read_po so that all the state is stored on a class. This is just because I found it more readable than having to use lists to store a single boolean which we wanted to update from inside the closures.

Support reading multi line obsolete units in po files

---

babel/messages/frontend.py

Before Babel 2.3, the input directories were always extracted 
in the order specified by the command line arguments.
For example, `pybabel extract dir_a dir_b dir_c` would process 
`dir_a` first, then `dir_b`, and finally `dir_c`.
Since Babel 2.3, the inputs are stored in a Python dictionary, 
and we loop over items in the dictionary using items().
This makes the order unspecified, not matching the order 
specified on the command line anymore.

Fix extraction order

---

babel/messages/catalog.py
tests/messages/test_pofile.py

When a .po file was written out it would write the "Language"
header, but it wouldn't subsequently read that header back in. This
change makes that symmetric so you can write out a file and get back the
same Catalog by reading it in again.
Additionally other values like charset get overridden when the header is
read, so codify the behavior that the read "Language" header gets set as
the locale of the Catalog object.
Fixes #422

Read locale from .po if it has Language header

---

babel/_compat.py
babel/numbers.py
babel/plural.py
babel/units.py
docs/numbers.rst
tests/test_numbers.py
tests/test_plural.py
tests/test_smoke.py

It turns out that the solution to allow the user to change the rounding mode was way simpler than expected at the beginning.
According to [UTS #35][1] sections [3.3][2] and [3.7][3], the user is allowed to change rounding mode.  But the default should be _half even_ mode.  This is already the default Python rounding mode in all decimal implementations, so the solution was to stop indicating the rounding mode on `Decimal` operations.
Some documentation has been added to show how to properly change the rounding mode and other `Context` parameters.
Therefore, this should fix #90 
[1]: http://www.unicode.org/reports/tr35/tr35-numbers.html
[2]: http://www.unicode.org/reports/tr35/tr35-numbers.html#Formatting
[3]: http://www.unicode.org/reports/tr35/tr35-numbers.html#Rounding

Allow full control on Decimal behaviour

---

babel/messages/extract.py
babel/util.py
tests/messages/test_extract.py

Python message extractor respects unicode_literals in __future__

---

babel/messages/catalog.py
babel/messages/plurals.py
tests/messages/test_catalog.py
tests/messages/test_plurals.py

This commit updates the plural rules, and in some cases the plural
number, for languages based on review of
https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals,
and
http://www.unicode.org/cldr/charts/29/supplemental/language_plural_rules.html.
I changed the interface (either the number of plurals, or the meaning
of each index), for the following languages:
• Arabic (ar): numplurals same, semantics differ per Mozilla's "Plural rule #12". 3 has been made more accurate, 4 has been switched with 5, and the meaning of both has been refined to match the rule.
• Belarusian (ar): numplurals updated to 3, using Mozilla's "Plural
rule #7". Previously the default, where anything except one is plural.
• Breton (br): numplurals updated to 6, using Mozilla's "Plural …

Updated plurals.py to match Mozilla and CLDR references

---

babel/messages/extract.py

The low-level extraction API is still terrible type-wise, though. (#80 and #140 are related to that issue.)
Fixes #403

Straighten up lying extraction docstrings

---

babel/plural.py
tests/test_plural.py

Fix float conversion in `extract_operands` (and the relevant test)

---

docs/dates.rst

Described recommendation to use "Y" with "w" for consistent results in ISO year-week and indicated possible surprising results for year rollover and total number of weeks in a year.

Improve Date Fields descriptions for issue #419

---

tests/messages/test_js_extract.py

b5e0ad8 fixed a few bugs with jsx parsing but only added
tests for the lexer. This commit adds a test for the extraction
which did not work before:
```
<tag>{ _"Text" }</tag>
```
This test case is not present yet in the suite, only tags with
attributes (`<tag attr="value">`) are, but they get extracted correctly
already.

Increase coverage of JSX extraction tests

---

babel/messages/frontend.py
babel/messages/pofile.py
tests/messages/test_frontend.py
tests/messages/test_pofile.py

Support of add_location option added, can be either 'full', 'file'
or 'never'. 'full' includes both file and line number; 'file' includes
only the file name without line number; 'never' doesn't include the
location comment at all (same as --no-location).
Python babel implementation lacks of this option. We would like to use it to avoid merge conflicts while merging po files.
Option `add_location` is implemented in the GNU xgettext, quote from the manual:
> ‘--add-location=type’
> 
> ```
> Generate ‘#: filename:line’ lines (default).
> 
> The optional type can be either ‘full’, ‘file’, or ‘never’. If it is not given or ‘full’, it generates the lines with both file name and line number. If it is ‘file’, the line number part is omitted. If it is ‘never’, it completely suppresses the lines …
```

Add option 'add_location' for location line formatting

---

babel/messages/pofile.py
tests/messages/test_pofile.py

Fixes the handling of the unit before the obsolete unit. Previously it would mark the unit before an obsolete unit as obsolete also.
Fixes multi-line msgctxt statements. Previously it would just take the first line.
Some refactoring:
- the transition between finishing one unit and starting the nextis clearer
- separate the processing of keywords and continuation lines
- combine the reset and initialisation code
- Make the handling of strings consistent.
- Add some nascent error handling, removed some errors in test inputs

Fix parsing pofile with obsoletes

---

babel/messages/frontend.py

Fix setup.py option 'add_location'

---

babel/localtime/_unix.py
babel/messages/catalog.py
babel/messages/jslexer.py
babel/plural.py
scripts/make-release.py

In Python, you can pass flags to regular expressions. There are two ways to do so: by passing the flag as a `flag` argument to whatever regex function you're using, or by embedding the flag in the regex itself. If the flag is embedded in the regex, it is ambiguous unless it is at the start of the expression, and in Python 3.6 this is now deprecated.
This pull request pulls all flags out of regexes and passes them via the `flag` argument, instead. This is clearer and more consistent.

Pull flags out of regular expressions

---

babel/messages/catalog.py
tests/messages/test_pofile.py

Sort translations according to msgid and msgctxt

---

babel/messages/extract.py
tests/messages/test_extract.py

This patch fixes #487.
There're only one small change and complex test cases.

Extract Python messages in nested gettext calls

---

babel/messages/catalog.py
tests/messages/test_pofile.py

Fixes #489
Augments #420 (08b9c5e76e19ae)

Allow both dash and underscore separated locale identifiers in pofiles

---

babel/messages/extract.py

This is a reissue of #476, since Git and Github and Travis were being silly.

Fixed in-place editing of dir list while iterating

---

babel/core.py
babel/numbers.py
scripts/import_cldr.py
tests/test_numbers.py

Add a couple of new utilities for currencies:
* `list_currency`: to list the whole set of currency codes supported by Babel.
* `validate_currency `.
* `is_currency `: to quickly validate if a currency is supported by Babel or not, not unlike what is currently available for locale (see: `babel.localedata.exists()`).
* `normalize_currency`: to normalize a currency string to the format expected by Babel.
* `get_currency_precision`: to get the natural precision of a currency.

Add currency utilities and helpers.

---

.travis.yml
Makefile
babel/localtime/_unix.py

In Python 3 this branch would never evaluate to `False` due to comparing a string to bytes.
This was flagged by running some unit tests with the `-bb` flag, so I've added
`-bb` to run with the babel unit tests in Python3.5
Here's some docs on the `-bb` flag:
https://docs.python.org/3.5/library/warnings.html#default-warning-filters
https://docs.python.org/3/howto/pyporting.html#use-continuous-integration-to-stay-compatible

Fix an invalid string to bytes comparison in Python 3

---

docs/messages.rst

The link to the python gettext module was dead in the doc. So, redirect the user
to the official doc.

Doc: always redirect to the python gettext module

---

CONTRIBUTING.md

Fixes the dead link with a new link to the same resource. Original issue [#345](https://github.com/python-babel/babel/issues/345) .

Fixes good comments link in CONTRIBUTING.md

---

babel/dates.py

Fixes Python 3 compatibility issue.

---

babel/core.py
babel/localedata.py
tests/test_localedata.py

Using a new module pi_support.py seems necessary, because there is no
possibility to use core.py or util.py.
These files are used inside setup.py at a time pytz is not yet installed.
This is a follow up to #504

Introduce PyInstaller support. Fixes #500

---

babel/dates.py

Use * parametrized format patterns in date formatting instead of %%0%...
This is about 60% faster than the old version in a micro-benchmark.

Slightly speed up date formatting

---

.ci/appveyor.yml
.travis.yml
tests/messages/test_frontend.py

freezegun library added to Travis build and Appveyor
Fixes #507
More details: https://github.com/python-babel/babel/pull/513

Using a fixed datetime to avoid test failures

---

babel/util.py
tests/test_util.py

Augments #426
Augments #427
Augments #510
Closes #510

Parse multi-line __future__ imports better

---

babel/numbers.py

The function raises a `UnknownCurrencyError` instead.

Fixed docstring of validate_currency function

---

babel/localedata.py
tests/test_localedata.py

made normalize_locale and exists to handle various unexpected input such as list or None just like currency, and added test cases in test_localedata.py
resolves: #521

modified normalize_locale and exists to handle various unexpected input

---

babel/localedata.py

Also check for `sys._MEIPASS` before assuming PyInstallerness
Fixes #525

Safer PyInstaller support

---

tox.ini

Travis config was updated in 1da04fd0af20162fe4e2b503a5fcae8f25267010 to address #520, and adds a dependency on `freezegun`. That dependency was  forgotten in `tox.ini`.

Keep tox dependencies in sync

---

babel/numbers.py
tests/test_numbers.py

This PR is refactoring the decimal handling code and:
* Adds extensive unittest of decimal-related rendering methods for percents, scientific notation and currencies.
* Deprecates `format_number()` in favor of `format_decimal()`.
* Fixes the way scientific numbers are rendered: patterns are now strictly respected, especially regarding the number of leading digits.
This PR is a preliminary work to prepare for #494, which adds more control over decimal quantization. The majority of these changes have already been extensively discussed in #494.

Decimal refactor

---

babel/numbers.py
tests/test_numbers.py

This PR add a `decimal_quantization` parameter to `format_decimal()`, `format_currency()`, `format_percent()` and `format_scientific()`, to bypass the forced quantization on the fractional part. This PR definitely address #90 and is a continuation of #410.
This PR has been extensively reviewed and is waiting for #538 to be merged, so I can rebase that one on top of it.

Decimal quantization

---

babel/core.py
babel/localedata.py
tests/test_localedata.py

PyInstaller+Babel was supported for quite a while before 2.5.0 - which broke support for this configuration by default. PyInstaller actually synthesizes a `__file__` for frozen aka bundled code that makes this "just work".
Closes #529.

Fix PyInstaller support

---

.travis.yml
babel/dates.py
babel/languages.py
babel/messages/catalog.py
babel/messages/checkers.py
babel/messages/frontend.py
babel/numbers.py
babel/plural.py
docs/dev.rst
setup.py
tests/messages/test_catalog.py
tests/messages/test_extract.py
tests/messages/test_frontend.py
tests/test_languages.py
tests/test_localedata.py
tests/test_numbers.py
tests/test_support.py
tox.ini

Further to https://github.com/python-babel/babel/pull/455, I'd like to suggest dropping support for Python 2.6 and 3.3. Both are EOL (2.6 for four years), meaning they no longer receive updates, including security updates. 
Removing them will help ease the maintenance burden, and allow to use more modern features of Python. Travis CI will also quicker, from ~23 min run time (total time ~1 hr 4 min) to ~11 min run time (total time ~43 min).
https://en.wikipedia.org/wiki/CPython#Version_history
See also:
* https://snarky.ca/stop-using-python-2-6/
* http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html
* http://www.python3statement.org
They're also little used. Here's the pip installs for babel from PyPI for the last month (via `pypinfo --percent --pip --markdown babel …

Drop support for EOL Python 2.6 and 3.3

---

babel/messages/pofile.py
tests/messages/test_pofile.py

This new exception is thrown when the po parser finds an invalid pofile.
This helps handle invalid po files that are parsed. Invalid po files may cause
other possible errors such as a UnicodeEncodeError.
Closes https://github.com/python-babel/babel/issues/531

pofile.py: Added new exception called PoFileError and thrown if flagged

---

docs/api/dates.rst

Because `default_locale` is eager, it generates misleading documentation when built (including on the site) as the doc will show the LC_TIME for the machine which built the doc.
An explicit autofunction signature fixes that and provides a more correct view of the signature. 
Alternative fix: have dates.LC_TIME be a custom object with a relevant repr e.g.
```python
class _LC(str):
def __new__(cls, category):
category = 'LC_' + category
v = str.__new__(cls, default_locale(category))
v._category = category
return v
def __repr__(self):
return "default_locale('%s')" % self._category
LC_TIME = _LC('TIME')
```

Add explicit signatures to some date autofunctions

---

.ci/appveyor.yml
.gitignore
.travis.yml
babel/core.py
babel/dates.py
babel/lists.py
scripts/download_import_cldr.py
scripts/import_cldr.py
setup.cfg
tests/test_dates.py
tests/test_lists.py
tests/test_numbers.py
tox.ini

This also improves support for list formatting, since this required changing the imported data format.

Use CLDR 32

---

docs/dates.rst

This is the result when following the tutorial:
```
>>> dt = datetime(2007, 04, 01, 15, 30, tzinfo=UTC)
File "<stdin>", line 1
dt = datetime(2007, 04, 01, 15, 30, tzinfo=UTC)
^
SyntaxError: invalid token
```
It should be written like this:
`>>> dt = datetime(2007, 4, 1, 15, 30, tzinfo=UTC)`
See: https://docs.python.org/3.5/library/datetime.html#datetime.datetime.month

Month and Day must be valid tokens

---

babel/numbers.py

This retains backwards compatibility (at least as far as the function's
signature is concerned) with users that are using NumberPattern.apply()
directly.
See: https://github.com/python-babel/babel/issues/550
See: https://github.com/python-babel/babel/issues/569
Also refs #494 and #538.

Restore force_frac to NumberPattern.apply() (as deprecated)

---

babel/messages/catalog.py
tests/messages/test_pofile.py

⚠️  This slightly changes the API of the Catalog object, so projects doing esoteric things with them (e.g. setting `.locale` post-fact) may break.
Fixes #553 
Fixes #555

Allow processing message files that are in locales unknown to Babel

---

scripts/import_cldr.py

Previously the script could have inadvertently merged formatting rules between numbering systems due to the XML selectors used.  This makes sure only Latin rules are used for the time being.  When support for other numbering systems is properly added (see #470), these checks can be changed.

import_cldr: ignore non-Latin numbering systems

---

babel/numbers.py
docs/api/numbers.rst
scripts/import_cldr.py
tests/test_numbers.py

numbers: implement currency formatting with long display names.

---

docs/_templates/sidebar-links.html
docs/numbers.rst

For details on the new PyPI, see the blog post:
https://pythoninsider.blogspot.ca/2018/04/new-pypi-launched-legacy-pypi-shutting.html

Update all pypi.python.org URLs to pypi.org

---

babel/numbers.py
docs/api/numbers.rst
tests/test_numbers.py

This branch adds a `strict` flag to the `parse_decimal` function. When set to `True` an exception is raised if the input number is formatted in a weird way. This is determined by comparing the string to the result of `format_decimal()`.
Closes #589.

Add a strict mode to `parse_decimal()`

---

setup.py

Here you use the utc attribute on the _pytz object: https://github.com/python-babel/babel/blob/23ca4bf2b187748e5e8372c6dae541fbcc5fbe5d/babel/util.py#L304
Which was added in this commit https://github.com/stub42/pytz/commit/ae82fbc71b374a5a5b32bf3bbb38ebb97af6e715
Corrected the version requirement to match the version where that attribute was added.

Bumped version requirement on pytz

---

babel/messages/pofile.py
tests/messages/test_pofile.py

A couple of very small fixes to avoid stack traces due to errors in the .po file.
1. Line 186
If a keyword - e.g. 'msgid' appears on a line by itself, the 'len(keyword)' call used to raise an IndexError exception rather than reporting the error
2. Line 293
If the offending line in the .po file contains unicode characters - e.g. accents - the 'format()' call was raising a UnicodeEncodeError rather than reporting the location of the error.

Small fixes to avoid stack traces due to badly formatted .po file

---

babel/util.py
tests/test_util.py

This PR adds support to `util.pathmatch` for forcing the match of the start of a string. This is useful for example if you want to place a `babel.cfg` file in a subdirectory and only extract messages from under that directory. The added (equivalent) syntax looks like so:
```ini
[python: ./**.py]
[python: ^**.py]
```

add support to util.pathmatch for matching the start of a string

---

babel/numbers.py
tests/test_numbers.py

Don't repeat suggestions for `0.00` in languages
which use commas as delimiters combined with strict
mode.
fixes #596

don't repeat suggestions in parse_decimal strict

---

babel/_compat.py
babel/localedata.py

And it will stop working in Python 3.8 according to the warning.

Using ABCs from collections instead of collections.abc is deprecated.

---

docs/installation.rst

easy_install is deprecated and its use is discouraged by PyPA:
https://setuptools.readthedocs.io/en/latest/easy_install.html
> Warning: Easy Install is deprecated. Do not use it. Instead use pip.
Follow upstream advice and only recommended supported tools.

Remove all references to deprecated easy_install

---

babel/localtime/_win32.py

I've found this issue trying to compile documentation with Sphinx on WindowsXP with `make html` command. Some data dictionaries are void on my machine, so using lazy 'get' on those can prevent next `KeyError`:
```
C:\Path\to\my\project\doc>make html
{'MapID': '8,9', 'Index': 165, 'Std': 'Hora estándar árabe', 'Display': '(GMT+04
:00) Abu Dhabi, Muscat', 'TZI': b'\x10\xff\xff\xff\x00\x00\x00\x00\xc4\xff\xff\x
ff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'Dlt': 'Hora de verano árab
e'}
{'MapID': '-1,71', 'Index': 158, 'Std': 'Hora estándar árabe D', 'Display': '(GM
T+03:00) Baghdad', 'TZI': b'L\xff\xff\xff\x00\x00\x00\x00\xc4\xff\xff\xff\x00\x0 …
```

Avoid KeyError trying to get data on WindowsXP

---

babel/_compat.py

The bytes type is available on all supported Pythons. On Python 2, it is an alias of `str`, same as `binary_type`. By removing the shim, makes the code more forward compatible.

Remove unnecessary compat shim 'binary_type'

---

CHANGES
babel/messages/catalog.py
babel/messages/frontend.py
babel/util.py
tests/test_util.py

The `odict` class duplicates `collection.OrderedDict` from Python's standard lib. Simplify the code by using builtin Python features.
https://docs.python.org/3/library/collections.html#collections.OrderedDict

Replace odict with Python's collection.OrderedDict

---

babel/messages/frontend.py

It is the same option as in extract_message but for when updating the
catalog.

frontend: Add  omit-header to update_catalog

---

babel/dates.py
tests/test_dates.py

The weeknumber was calculated to 53, but by definition the value
must compute to 1.
the fix will compute the weeknumber by using date.isocalendar if
locale.first_week_day == 0.
Also the computation of the year format 'YYYY' is replaced by isocalendar.
Tests added.
Fixes https://github.com/python-babel/babel/issues/619

fixes #619 wrong weeknumber for 31.12.2018

---

.ci/appveyor.yml
.travis.yml
tests/conftest.py
tox.ini

While pytest in tox.ini is explicitly set to be 3.3.2, in Fedora 31 we are about to update to a newer version of pytest. In order to be able to test babel, we need pytest 4.3 support.
This adds support for pytest 4.3 without breaking support for 3.3.2.
Switching to 4.3 in tox.ini is left at the discretion of the maintainers.

Fix conftest.py compatibility with pytest 4.3

---

babel/localedata.py
tests/test_localedata.py

Fixes #620
This speeds up the test code from #620 19-fold on my machine:
```
(babel) ~/b/babel (master) $ python exp_issue_620.py
7.1793154459999995
(babel) ~/b/babel (cache-locale-identifiers) $ python exp_issue_620.py
0.359975983
```

Cache locale_identifiers()

---

babel/messages/pofile.py
tests/messages/test_normalized_string.py

* Add comparison operators to _NormalizedString (fixes #612)
* Don't crash when message.locations can't be sorted (leave them unsorted) (fixes #606)

Message comparison fixes

---

babel/messages/catalog.py
tests/messages/test_catalog.py

The assumption here is that the template wouldn't contain user comments to begin with, being autogenerated.
Closes #418 (supersedes; adds tests)

Catalog update: keep user comments from destination by default

---

babel/numbers.py
setup.cfg
tests/test_numbers.py

parse_decimal(): Parse spaces as group separators if the group separator is nbsp

---

babel/messages/pofile.py

see issue #606.  if one object has anything that doesn't compare to `int`, bring it to the top, and correctly sort the rest.

attempt partial sorting at least

---

babel/messages/extract.py
babel/numbers.py
tests/test_numbers.py

Includes the code from these two PRs:
* Closes #662
* Resolves #636 
* Closes #678

Fix amalgamation

---

babel/util.py

Replaced usage of the long-superseded "parser.suite" module in the mako.util package for parsing the python magic encoding comment with the "ast.parse" function introduced many years ago in Python 2.5, as "parser.suite" is emitting deprecation warnings in Python 3.9.
Fixes https://github.com/sqlalchemy/mako/issues/310
See also https://github.com/sqlalchemy/mako/commit/2dae7d2c3da73653e6de329dc15c55056a0b9ab6

Replace usage of parser.suite with ast.parse

---

babel/messages/pofile.py
tests/messages/test_pofile.py

Until now, on Python 2.7, `python setup.py test | cat` crashed in the test
runner with
======================================================================
ERROR: test_abort_invalid_po_file (tests.messages.test_pofile.ReadPoTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
File "src/babel/tests/messages/test_pofile.py", line 458, in test_abort_invalid_po_file
output = pofile.read_po(buf, locale='fr', abort_invalid=False)
File "src/babel/babel/messages/pofile.py", line 377, in read_po
parser.parse(fileobj)
File "src/babel/babel/messages/pofile.py", line 310, in parse
self._process_message_line(lineno, line)
File "src/babel/babel/messages/pofile.py", line 210, in _process_message_line
self._process_keyword_line(lineno, …

Fix unicode printing error on Python 2 without TTY.

---

docs/api/messages/catalog.rst

The declaration of \_\_iter__ under the special-members
directive makes it visible in the documentation.
The docstring describing \_\_iter__ already exists.
Closes https://github.com/python-babel/babel/issues/128

catalog.rst: Add __iter__ to Catalog documentation

---

scripts/import_cldr.py
tests/test_util.py

This fixes the test suite when using Python 3.9a6. Also it includes my fix from #710 for the `import_cldr.py` script.
Fixes #709

compatibility with Python 3.9a6

---

docs/numbers.rst

Update the documentation of the parse_number function to reflect working but limited functionality at this time.
Closes https://github.com/python-babel/babel/issues/692

docs/numbers.rst : update parse_number comments

---

babel/numbers.py
tests/test_numbers.py

Added a new **group_separator** feature in number formatting. **group_separator** is a Boolean parameter default set as `True`, when `False`, it simply means the output should be free of group separator.
Example:
```
format_decimal(23434567890567.1224, locale='fr_CA', group_separator=False)
>>> '23434567890567,12'
```
Default behaviour remains unchanged.
Example:
```
format_decimal(23434567890567.1224, locale='en_US')
>>> '23,434,567,890,567.12
```

Added group_separator feature in number formatting

---

babel/support.py
tests/test_support.py

Fixes https://github.com/python-babel/babel/issues/723

LazyProxy: Handle AttributeError in specified func

---

babel/messages/catalog.py

Matches the behavior elsewhere in the same function
Closes #698

Use 'if not' instead of 'if ... is False' for no_fuzzy_matching

---

.ci/appveyor.yml
.travis.yml
babel/dates.py
tests/test_dates.py
tox.ini

Python 3.9 introduced ZoneInfo objects, and they are available as a [backport](https://pypi.org/project/backports.zoneinfo/) back to python 3.6.
This PR adds support for these objects.
Fixes https://github.com/python-babel/babel/issues/740

Handle ZoneInfo objects in get_timezone_location, get_timezone_name

---

.coveragerc
babel/support.py
babel/units.py
scripts/download_import_cldr.py
scripts/import_cldr.py
tests/test_support.py

This PR adds support for CLDR 37 (published 2020-04).
No new features (prefix compound patterns, grammatical forms) are supported at this time.
It also cleans up some deprecation warnings in certain tests.

CLDR 37 support

---

babel/messages/frontend.py
tests/messages/test_frontend.py

Currently, if an output `.po` file doesn't exist during `pybabel update`, the update fails when trying to open the missing file. This PR adds a boolean `--init-missing` option. If this option is enabled during an update and an output `.po` file is missing, it is created and initialized the same way it would be by `pybabel init`.
---
**Before this PR** you had to run two commands like
```sh
pybabel init   --domain=${DOM} --locale=${LOC} --input-file=pot/${DOM}.pot --output-dir=po/
pybabel update --domain=${DOM} --locale=${LOC} --input-file=pot/${DOM}.pot --output-dir=po/
```
if `po/${LOC}/LC_MESSAGES/${DOM}.po` didn't exist.
If the file **did** already exist, you had to only run the second command (otherwise, running `init` on an existing file overwrites it, removing any previous …

Implement `--init-missing` option for `pybabel update`

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md

Replaces "Filling issues" contributing guide section by Github template, so if an user open an issue, the needed text is already included.

Add Github issue template

---

babel/dates.py
tests/test_date_intervals.py

Date intervals: allow using `other` as fallback form

---

babel/core.py
tests/test_core.py

Upper-casing the variant tag should be okay, since quoth [the spec](https://datatracker.ietf.org/doc/html/rfc5646#section-2.1.1):
>   At all times, language tags and their subtags, including private use
>  and extensions, are to be treated as case insensitive: there exist
>  conventions for the capitalization of some of the subtags, but these
>  MUST NOT be taken to carry meaning.
Fixes #814

parse_locale(): upper-case variant tag to match file system

---

.github/workflows/test.yml
.gitignore
Makefile
tox.ini

This PR fixes Codecov reporting, which has been broken for a while.

Fix Codecov

---

babel/messages/extract.py
babel/messages/frontend.py
tests/messages/data/project/_hidden_by_default/hidden_file.py
tests/messages/test_frontend.py

This PR:
* adds a `directory_filter` callback argument to `extract_from_dir` that defaults to the current behavior of ignoring dot and underscore directories
* adds a frontend `--ignore-dirs` (that can be repeated) to replace the default `.*` / `_*` filtering with other patterns
---
Fixes #53 – set `--ignore-dirs` to disable the default dot and underscore filters
Fixes #402 – implements it :)
Refs #124 – there is still no way to set this in the mapping configuration file, though (that's #694)
Refs #253 – one could now `--ignore-dirs=node_modules`, for instance.
Refs #694 – could be reimplemented on top of this `directory_filter`?
Closes #447 – supersedes it
Closes #563 – supersedes it
Closes #761 – you can set `--ignore-dirs='.*'`
Closes #813 – supersedes it (thanks for the wording for …

Implement directory filter for extract

---

babel/dates.py
tests/test_dates.py

Fixes #442
Fixes #657
Closes #448 (supersedes it)
Closes #767 (supersedes it)
Closes #659 (supersedes it)

Improve date/time parsing

---

babel/messages/catalog.py

Parsing a date time string (such as for ``POT-Creation-Date`` or
``PO-Revision-Date``) as UTC time, in particular independent of the
local time zone.
Closes: #700

Parse string date times indepentent of time zone

---

babel/support.py
setup.cfg
tests/test_numbers.py

Quenches some test warnings.
Refs https://github.com/python-babel/babel/issues/802#issuecomment-1029133205

Don't use the deprecated format_number function internally or in tests

---

babel/messages/pofile.py
tests/messages/test_pofile.py

If the same translation appears multiple times in the same file,
duplicate locations would be written to the .po file when using
`write_po(..., include_lineno=False)`.

Fix duplicate locations when writing without lineno

---

babel/messages/frontend.py
setup.py
tests/messages/test_frontend.py

Considering distutils is being deprecated, this fixes up things so imports from `setuptools` are used where available instead.
The non-conditional imports have been around for 6 to 17 years, so they should be safe in conservative situations too.
Refs #824

Prefer setuptools imports to distutils imports

---

babel/support.py

Fixes #819 (even if Python 3.11 is only due around 2022-10-03).

Gettext deprecation fixes (for Python 3.11 compatibility)

---

babel/messages/frontend.py
tests/messages/test_frontend.py

This adds a unit test for the `--list-locales` argument, and updates its implementation to not output bytes reprs.
In other words, goes from this:
```
...
b'fr_CH           French (Switzerland)'
b'fr_CI           French (C\xc3\xb4te d\xe2\x80\x99Ivoire)'
b'fr_CM           French (Cameroon)'
...
```
to this
```
...
fr_CH           French (Switzerland)
fr_CI           French (Côte d’Ivoire)
fr_CM           French (Cameroon)
...
```

Fix output of --list-locales to not use bytes reprs

---

babel/messages/catalog.py
babel/messages/frontend.py
tests/messages/test_frontend.py

I was missing a way to, as a part of CI-pipeline, check if the translations files are up to date. This PRs attempts to implement it in form of a `--check` flag for `pybabel update`.

Provide a way of checking if the catalogs are up-to-date

---

babel/dates.py

In preparation of removing the hard dependency on pytz.
Refs #716

Deprecate get_next_timezone_transition()

---

babel/messages/frontend.py
tests/messages/test_frontend.py

allow header_comment to be passed as an option to extract_message

---

tests/test_dates.py

Add test for issue #798

---

babel/core.py

30s typo fix.
`langauge`->`language`

chore(docs/typo): Fixes a minor typo in a function comment

---

babel/numbers.py
tests/test_numbers.py

Fallback count="other" format in format_currency()

---

babel/dates.py
tests/test_day_periods.py

Fix get_period_id() with `dayPeriodRule` across 0:00

---

babel/dates.py
tests/test_dates.py

Add support for `b` and `B` period symbols in time format

---

tests/messages/test_catalog.py
tests/messages/test_extract.py
tests/messages/test_frontend.py
tests/messages/test_mofile.py
tests/messages/test_pofile.py
tests/test_dates.py
tests/test_localedata.py
tests/test_numbers.py
tests/test_support.py
tests/test_util.py

Automated conversion initially applied with https://github.com/warlo/codemod-unittest-to-pytest-asserts, followed by some manual changes for brevity.
Almost no functional changes to the tests here.

tests: Use bare asserts and pytest.raises

---

babel/messages/catalog.py
tests/messages/test_pofile.py

cgi.parse_header is due to be deprecated.
Fixes #873

Use email.Message for pofile header parsing

---

babel/localtime/_win32.py
scripts/download_import_cldr.py
scripts/import_cldr.py

I came across `shutil.get_terminal_size()` and remembered there was a homespun implementation of it in the downloader script, so this replaces it, and fixes up the downloader a bit in other senses too.
I also realized there were some no-longer-relevant import guards around, so away with them too.

Small downloader improvements

---

docs/dev.rst

Also remove mentions of Python 2 workarounds, since they aren't applicable anymore.

Update Python versions in dev docs

---

babel/messages/pofile.py
babel/support.py

`__nonzero__` is not used in python3, instead we now use `__bool__`.
Since `setup.py` declares to support `python >= 3.6`, I guess it is safe to remove these methods.
`setup.py`: https://github.com/python-babel/babel/blob/d8584405a66a79d79bed44b5d80df0bc89f8eee3/setup.py#L59

Remove `__nonzero__` methods

---

babel/dates.py
babel/support.py

The `__unicode__` protocol is not used in python3, and furthermore the `unicode()` builtin does not exist anymore.
I found this while browsing through the source code and given that babel requires ≥3.6 I thought I could just open a PR.

Remove superfluous `__unicode__` declarations

---

babel/messages/jslexer.py
tests/messages/test_jslexer.py

Currently Babel only supports `\u`-style Unicode escapes in JavaScript string literals.
Unfortunately, I have to deal witth JS files (WebPack-generated) that contain `\x`-style escapes. I believe Babel should support it, as it's perfectly legitimate JS syntax.

Support for hex escapes in JavaScript strings

---

babel/localtime/_unix.py

According to [this post](https://truesecdev.wordpress.com/2015/04/09/hidden-backdoor-api-to-root-privileges-in-apple-os-x/comment-page-1/) the `systemsetup` command has required superuser privileges since macOS 10.8.5 (which has been EOL for over 6 years at the time of writing).
We shouldn't expect to use a codepath that requires a helper tool that requires su in any regular use; IOW, _if_ a Babel user had ever reached this path without having been superuser, it would have failed anyway on any currently supported version of macOS.
Closes #895 (supersedes it).

Remove determining time zone via systemsetup on macOS

---

babel/dates.py

As the subject says: the changes should allow for transparent parsing of ISO dates, I added corresponding tests

Adapt parse_date to handle ISO dates

---

babel/messages/extract.py
tests/messages/test_extract.py

This is safer (as we don't actually execute anything), and allows us to parse f-strings too.
Closes #769 (supersedes it)
Refs #715 (doesn't add an error yet, but doesn't crash on f-strings)

Use `ast` instead of `eval` for string extraction

---

CHANGES.rst

Some links in CHANGES.rst are not linking directly to the corresponding issues properly. The extra `#` sign was causing it to be treated as a url hash on the issue listing page.

docs(changes): Fix broken issue links

---

babel/support.py
tests/test_support.py

Adds a shortcut to Format support utility for `compact_decimal`
```py
>>> fmt = Format('en_US')
>>> fmt.compact_decimal(123456789)
u'123M'
```

feat: Adds `Format.compact_decimal` utility

---

babel/numbers.py
tests/test_numbers.py

Fixes #929 
Division does not work with decimal.Decimal. This uses `//` so integer division is performed instead.
`abs` and `round` don't work with strings. This converts the number to a Decimal so that `_get_compact_format` won't raise a ValueError as long as the number supports Decimal conversion. Also has a fix for how [rounding modes](https://babel.pocoo.org/en/latest/numbers.html#rounding-modes) are treated.
This adds support for `decimal.Decimal` and `str` types to the number parameter of `format_compact_*` functions.
```py
>>> from babel.numbers import *
>>> import decimal
>>> format_compact_decimal(decimal.Decimal("1000"))
"1K"
>>> format_compact_decimal("1000")
"1K"
```

Cast number to Decimal in _get_compact_format

---

.github/workflows/test.yml

`tox-gh-actions` v2 does not support `tox` v4.
Since tox does not have a version specified, this was causing the workflow to fail.
When `tox-gh-actions` v3 is released, `tox` can change to v4.

ci: Fix testing dependencies

---

babel/numbers.py
test.py
tests/test_numbers.py

Fixes #931
* Adds support for patterns with no numbers
* In compact format, only uses "one" format if the number pluralizes to "one" *before* rounding
* In compact format, [explicit "1" formats](https://unicode.org/reports/tr35/tr35-numbers.html#Explicit_0_1_rules) can now be applied (there [seem to be none](https://gist.github.com/DenverCoder1/9c34fb012cefdc75f8d53724c24fe260) with explicit "0" formats)
```py
>>> numbers.format_compact_decimal(1000, format_type='long', locale='it')
'mille'  # previously 'mille1'
>>> numbers.format_decimal(1, format="mille")
'mille'  # previously 'mille1'
>>> format_compact_decimal(21098765, format_type="long", locale="mk")
'21 милиони'  # previously '21 милион' (would still be singular if the number were 21000000)
>>> numbers.format_compact_decimal(1000, …
```

Fix compact singular formats and patterns with no numbers

---

babel/dates.py
babel/localtime/__init__.py
babel/localtime/_unix.py
babel/localtime/_win32.py
babel/messages/catalog.py
babel/messages/frontend.py
babel/numbers.py
babel/support.py
babel/util.py

Various modules in Babel imported `datetime` in various ways, sometimes needing aliases and whatnot; this commit unifies everything to `import datetime`.

Unify datetime imports

---

babel/core.py
babel/dates.py
babel/numbers.py
babel/support.py
scripts/download_import_cldr.py
scripts/import_cldr.py
tests/test_core.py
tests/test_date_intervals.py
tests/test_dates.py
tests/test_numbers.py
tests/test_support.py

Fixes #942.
As a double-check, the space changes around English seem to be on purpose, see  https://unicode-org.atlassian.net/browse/CLDR-14032 / https://github.com/unicode-org/cldr/commit/a83026ab8c8fa6ed88f1047c4d0c6089f88b7e5d

Upgrade to CLDR 42

---

.github/workflows/test.yml
tox.ini

Since tox-gh-actions has a stable release supporting tox v4, both dependencies can be updated.
To test with tox v4, `whitelist_externals` needs to be replaced with `allowlist_externals`.
Also updates codecov/codecov-action from v2 to v3.
* https://tox.wiki/en/latest/upgrading.html
* https://github.com/codecov/codecov-action#migration-from-v1-to-v3

Update test dependencies (tox v4)

---

babel/support.py
tests/test_support.py

The doctests test the exact same things.

Remove redundant tests for babel.support

---

babel/numbers.py
tests/test_numbers.py

This came up while I was looking for ways to improve type-safety - specifically that the type of `decimal_tuple.exponent` in `get_decimal_precision()` is `int | Literal['n', 'N', 'F']` and can't be compared with 0 or taken the absolute value of if it is not an int.
This fixes that type issue but I'm making this a separate PR since it also fixes NaN and Infinity cases in other areas, so it won't raise exceptions when formatting.
Fixes #132 
```py
>>> format_decimal(decimal.Decimal('Infinity'))
'∞'
>>> format_decimal(decimal.Decimal('-Infinity'))
'-∞'
>>> format_decimal(decimal.Decimal('NaN'))
'NaN'
```

Support for formatting NaN, Infinity

---

babel/dates.py

See https://stackoverflow.com/a/24271786/51685
My bad! I had remembered the behavior to be like with Python 2...

Fix unbound `exc` in babel.dates

---

babel/dates.py
docs/api/dates.rst
docs/dates.rst

This had been slated for removal in 2.11, but was left in for a while.
See https://github.com/python-babel/babel/issues/716

Finally remove get_next_timezone_transition

---

babel/core.py
babel/dates.py
babel/localedata.py
babel/localtime/_fallback.py
babel/messages/extract.py
babel/messages/frontend.py
babel/messages/pofile.py
babel/numbers.py
babel/plural.py
babel/support.py

More fixes and modernization

---

babel/core.py
tests/test_core.py

Locale modifiers ("@variants") are described in the GNU gettext documentation like this:
> The ‘@variant’ can denote any kind of characteristics that is not
> already implied by the language ll and the country CC. […] It can also
> denote a dialect of the language, …
Wherein Babel previously would discard these, this patch stores the modifier information in the `Locale` objects, handling string representation accordingly.
Not implemented is the lookup of a meaningful description of modifiers, but instead — for now — an identity mapping is provided.
All tests pass. Furthermore, integration with `flask-babel` has been verified to work.
Resolves: #946
Signed-off-by: martin f. krafft <madduck@madduck.net>

Keep @modifiers when parsing locales

---

docs/cmdline.rst

Options added in the pull requests #720 and #832 are missing in the documentation. This pull request fixes it.

Add two new options in cmdline.rst docs

---

babel/core.py
babel/numbers.py

Type annotation improvements:
1. Changed `Locale.parse` to always return a `Locale` (this fixes type issues in multiple places where the return type is assumed to not be None)
2. Fixed Pyright type errors and added `type: ignore` in certain places in core.py and numbers.py
**Note:** Changing `Locale.parse` to always return a `Locale` simplifies the logic, but it also can potentially be a breaking change if people are relying on passing `None` not raising an exception. It is a bit of a stretch though, since passing `None` has no functional effect in the use of the lib.
These changes have been separated from #961

Numbers and core type fixes

---

babel/dates.py
babel/localedata.py
tests/test_localedata.py

Fixes #962 (unbounded cache memory leak)

Use lru_cache where suitable

---

babel/messages/catalog.py
tests/messages/test_catalog.py

- One issue with case,
- One issue with difflib's “autojunk” heuristic.
Fixes #969

Fix two issues with fuzzy matching

---

setup.py

#934 by @DenverCoder1 added inline type annotations and a `py.typed` file, which is great! Unfortunately, however, the `py.typed` file hasn't been included in wheels published to PyPI for v2.12.0. This means that if I `pip install` babel locally, mypy still doesn't recognise `babel` as a typed library. Running mypy on a file with just `import babel` in it results in this output from mypy (unless the typeshed `types-babel` package is installed):
```
test.py:1: error: Library stubs not installed for "babel"  [import]
test.py:1: note: Hint: "python3 -m pip install types-babel"
test.py:1: note: (or run "mypy --install-types" to install all missing stub packages)
test.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 …
```

Include `py.typed` file in wheels

---

CHANGES.rst
babel/core.py

Note that `Locale.parse()` does not accept `None`

---

babel/messages/catalog.py

babel.messages.catalog: deduplicate _to_fuzzy_match_key logic

---

babel/support.py

Improve type annotation for `babel.support.Translations.load`

---

CONTRIBUTING.md
Makefile
setup.py
tox.ini

Improve contributing instructions

---

babel/dates.py
docs/dates.rst
tests/test_dates.py

Avoids deprecation warnings on Python 3.12.

Use aware UTC datetimes internally

---

babel/messages/catalog.py
babel/messages/frontend.py
tests/messages/test_catalog.py
tests/messages/test_frontend.py

Adding a flag to ignore changes to POT-Creation-Date when performing updates or checks. 
I use a CI check that ensures my .po files are updated before merging, but there is always a diff on POT-Creation-Date.
Related to https://github.com/python-babel/babel/issues/725 - but solving (my) problem via update instead of extract.

Add flag to ignore POT-Creation-Date for updates

---

babel/messages/extract.py
babel/messages/frontend.py
docs/cmdline.rst
tests/messages/test_frontend.py

Support 't' specifier in keywords

---

babel/messages/extract.py

Since Python 3.12, f-strings are tokenized and parsed like the rest of Python's grammar, using the new tokens `FSTRING_START`, `FSTRING_MIDDLE` and `FSTRING_END`, as described in [pep 701 #new-tokens](https://peps.python.org/pep-0701/#new-tokens).
Make the babel message extractor concatenate these three if they're adjacent to each other. If they're not, that means there are dynamic substitutions, so the f-string is ignored.

Add f-string parsing for Python 3.12 (PEP 701)

---

setup.py
tox.ini

The dependency was already added specifically for CI, but that is not correct, because it's the package itself that actually depends on setuptools
* Fixes #1031

Depend on setuptools since Python 3.12

---

babel/support.py

Call str() on the parameter variable instead of the module object.

Fix _locales_to_names (Fix for #1037)

---

babel/core.py
scripts/download_import_cldr.py
scripts/import_cldr.py

This upgrades the CLDR database to release 43.
I tried upgrading to 44 initially, but there seemed to be a lot of breaking changes in there that I didn't know how to deal with, and the locales I'm personally interested in are already supported in 43.
I had to make two additional changes in addition to updating the import:
One doctest, regular spaces have been replaced by thin spaces
In the importing of `parentLocales`. The new `supplementalData.xml` contains a new type of declaration:
```
<parentLocales component="collations">
...
<parentLocale parent="sr_ME" locales="sr_Cyrl_ME"/>
....
</parentLocales>
```
This refers to a locale called `sr_ME`, but there is no `.xml` file for it and so no `.dat` file gets generated either. At runtime, when the locale for `sr_Cyrl_ME` is looked up, we …

Upgrade to CLDR 43

---

.pre-commit-config.yaml
babel/messages/frontend.py
babel/messages/setuptools_frontend.py
conftest.py
setup.py
tests/messages/consts.py
tests/messages/test_frontend.py
tests/messages/test_setuptools_frontend.py
tox.ini

Decouple `pybabel` frontend from distutils/setuptools; remove dependency

---

babel/messages/frontend.py
tests/messages/test_frontend.py

Commit allows to pass last translator to the CLI.
For example,
`pybabel extract --last-translator=test@test.test`

Allow last_translator to be passed as an option to extract_message

---

babel/core.py
babel/numbers.py
babel/support.py
babel/units.py
scripts/import_cldr.py
tests/test_core.py
tests/test_numbers.py
tests/test_smoke.py
tests/test_support.py

Changes:
- Load number symbols for multiple number systems from cldr data
- Add numbering_systems and default_numbering_system properties for Locale
- Use default numbering system of the locale for formatting number symbols
Example:
Before:
```
>>> numbers.format_decimal(123456789.01234, locale="fa_IR")
'123,456,789.012'
```
Now:
```
numbers.format_decimal(123456789.01234, locale="fa_IR")
'123٬456٬789٫012'
```
Fixes partially issue:https://github.com/python-babel/babel/issues/446
I took some inspiration from the closed PR: https://github.com/python-babel/babel/pull/470
Couple questions:
- How much do we have to care about backward compatibility? Is it okay that this changes the numbering system used for formatting symbols from `latn` to the default numbering system for locales which …

Add support of local numbering systems for number symbols

---

babel/numbers.py
tests/test_numbers.py

Fixes #928
Problem:
The current code was primarily designed for numbers like `3,400.00`, where the r-stripped value (`3,400.`) matches the expected `proper` (`3,400`) + `.` (`3,400.`) format. It doesn't work for numbers like `3,400.60` since `3,400.6` (the value after r-stripping) is incorrectly perceived as not equal to the expected format, which is the `proper` (`3,400.6`) + `.` (`3,400.6.`), thereby leading to its erroneous detection as improperly formatted. 
Solution:
Added a more robust method for stripping trailing zeros, specifically targeting only those zeros that appear after the last non-zero digit following the decimal symbol.

fix(numbers): correctly determine malformed decimals

---

babel/numbers.py
tests/test_numbers.py

The French group separator is `"\u202f"` (narrow non-breaking space), but when parsing numbers in the real world, you will most often encounter either a regular space character (`" "`) or a non-breaking space character (`"\xa0"`).
The issue was partially adressed earlier in https://github.com/python-babel/babel/issues/637, but only to allow regular spaces instead of non-breaking spaces `"\xa0"` in `parse_decimal`.
This PR goes further by changing both `parse_number` and `parse_decimal` to allow ~~any other space character (using the `\s` character class of regular expressions)~~ any of those 3 space characters when the expected group symbol is itself one such space character, but is not present in the string to parse.
Unit tests are included.

Allow alternative space characters as group separator when parsing numbers

---

babel/messages/extract.py

Running the tests under python 3.12 I get deprecation warnings related to the usage of `ast.Str` which has been deprecated since 3.8 and will be removed in 3.14.
Since 3.8 is also the lowest version supported by babel, we can safely make the change to use `ast.Constant` everywhere.

Replace deprecated `ast.Str` with `ast.Constant`

---

babel/localedata.py
scripts/download_import_cldr.py
scripts/import_cldr.py
tests/test_localedata.py
tests/test_numbers.py

[CLDR 45](https://cldr.unicode.org/index/downloads) is out now.
Looks like the 44 patch fixed most of the test issues so there was only one failing test this time around :)
Some related discussion here: #1070

Upgrade to CLDR 45

---

babel/support.py
tests/test_support.py

Given this po file:
```po
msgctxt "ctx"
msgid "foo"
msgid_plural "foos"
msgstr[0] "foo translated"
```
`pgettext` fails to find the singular translation i.e. `pgettext("ctx", "foo") == "foo"` when one would expect to get `foo translated`.
The same issue has already been fixed upstream in `gettext`: 
https://github.com/python/cpython/issues/62519
https://github.com/python/cpython/pull/107118
This PR applies the same patch to babel.

Make pgettext search plurals when translation is not found

---

tests/messages/test_frontend.py

frontend.py: Fix function argument
Previosly in function was passed raw value `self.ignore_dirs`, not a list as expected `ignore_dirs`.
- https://github.com/python-babel/babel/pull/832

Fix for #832

---

babel/localtime/_helpers.py
tests/test_localtime.py

Fixes #1092.
When `pytz` is _not_ installed, importing `babel.localtime` could fail (repeatedly) when the `TZ` environment variable is malformed enough to be caught by [`_validate_tzfile_path`](https://github.com/python/cpython/blob/ac0745111/Lib/zoneinfo/_tzpath.py#L85), which might throw a certain `ValueError`.
(When `pytz` is installed, it would raise the same `pytz.exceptions.UnknownTimeZoneError` we already catch and ignore for the same input.)

Avoid crashing on importing localtime when TZ is malformed 

---

babel/dates.py

Based on the discussion here: #1084 
This should make it clearer that fuzzy matching might still fail to find a suitable pattern.

Add a mention to the docs that `format_skeleton(..., fuzzy=True)` may raise

---

scripts/download_import_cldr.py
scripts/import_cldr.py
tests/test_core.py

For more coverage, we've allowed using alternate or draft values when no officially accepted values have been present.
However, non-global (i.e. e.g. `de_CH` locales) may have an alternate spelling for what would be an alternate in the parent locale (and that alternate hasn't been imported into the parent), and the import would have then accepted the alternate from the child locale as a non-alternate.
Fixes #1112.

Do not allow substituting alternates or drafts in derived locales

---

docs/dev.rst

Two hyperlinks (to CLDR) and some typos

---

babel/messages/frontend.py
tests/messages/test_frontend.py
tests/messages/test_toml_config.py
tests/messages/toml-test-cases/bad.extractor.toml
tests/messages/toml-test-cases/bad.extractors-not-a-dict.toml
tests/messages/toml-test-cases/bad.just-a-mapping.toml
tests/messages/toml-test-cases/bad.mapping-not-a-dict.toml
tests/messages/toml-test-cases/bad.mappings-not-a-list.toml
tests/messages/toml-test-cases/bad.missing-extraction-method.toml
tests/messages/toml-test-cases/bad.multiple-mappings-not-a-list.toml
tests/messages/toml-test-cases/bad.non-string-extraction-method.toml
tests/messages/toml-test-cases/bad.pattern-type-2.toml
tests/messages/toml-test-cases/bad.pattern-type.toml
tests/messages/toml-test-cases/bad.pyproject-without-tool-babel.toml
tests/messages/toml-test-cases/bad.standalone-with-babel-prefix.toml

This PR offers to implement part of https://github.com/python-babel/babel/issues/777.
Namely, following this PR you would be able to run `pybabel extract -F babel.toml` – or even `pybabel extract -F pyproject.toml`, as we already will support `tool.babel` as well as `babel` for the namespace. (Auto-detecting a `pyproject.toml` instead of `setup.cfg` or `babel.cfg` is not implemented in this PR.)
I'm **requesting comments** on the proposed TOML format, which borrows the idea of [mappings-as-lists from Mypy's overrides configuration](https://mypy.readthedocs.io/en/latest/config_file.html#example-pyproject-toml).
```toml
[babel.extractors]
custom = "mypackage.module:myfunc"
[[babel.mappings]]
method = "python"
pattern = "**.py"
[[babel.mappings]]
method = "genshi"
pattern = …
```

Initial support for reading mapping configuration as TOML

---

tests/test_dates.py

This shows up when running the tests on 3.12:
```python
~dev/babel/tests/test_dates.py:757: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to rep
resent datetimes in UTC: datetime.datetime.now(datetime.UTC).                                                                                                                                 
assert dates.format_datetime(datetime.utcnow(), locale="ja_JP@mod")
```
I think there's no harm in using plain `datetime.now()` for these tests.

Fix deprecation warnings for `datetime.utcnow()`

---

babel/dates.py
tests/test_dates.py

`str.index` raises a `ValueError` when the substring is not found so there is no way to even check the return value as the code currently tries to do. Replacing it with `str.find` makes the code work as intended.

Replace `str.index` with `str.find`

---

babel/dates.py
tests/test_dates.py

Related discussion: #1084 
Replaces some additional characters which never appear in resource files before matching the skeleton. This replicates the behaviour of ICU: https://github.com/unicode-org/icu/blob/5e22f0076ec9b55056cd8a84e9ef370632f44174/icu4j/main/core/src/main/java/com/ibm/icu/text/DateIntervalInfo.java#L1090-L1102

Replace more alternate characters in `format_skeleton`

---

babel/messages/extract.py
tests/messages/test_extract.py

When a gettext call had a nested function call on a new line, the extract function would use that nested call's line number when extracting the terms for the gettext call.
The reason is that we set the line number on any encounter of an opening parenthesis after a gettext keyword. This does not work if either we have a nested call, or our first term starts on a new line.
This commit fixes that by only setting the line number when we encounter the first argument inside a gettext call.
Existing tests were adapted to work according to `xgettext` with regards to the line numbers.
Fixes https://github.com/python-babel/babel/issues/1123

Fix extracted lineno with nested calls

---

babel/messages/pofile.py
tests/messages/test_pofile.py

Addresses https://github.com/python-babel/babel/issues/1134
Previously, the `add_message` function would try to access the PoFileParser object's translations list without any checks. However, when an invalid po file is provided, this can lead to an index out of range error.
This PR adds a check to the `_finish_current_message` function and raises an `invalid_pofile` exception when the messages list is populated and translations is empty. This also adds a dummy translation to the translations list to avoid the index out of range error when an `invalid_pofile` exception is treated as a warning rather than raised.

Fix of list index out of range error in PoFileParser.add_message when translations is empty

---

babel/dates.py
tests/test_dates.py

This addresses the crash by making the seconds optional. If the time format only contains house and minutes, seconds are assumed to be zero.
closes #1129

Make seconds optional in `parse_time` time formats

---

babel/messages/pofile.py
babel/util.py

Mark `wraptext` deprecated; use `TextWrapper` directly in `write_po`

---

babel/messages/pofile.py
tests/messages/test_pofile.py

Closes #1124 
Previously, the `Catalog.obsolete` dictionary would use the `msgid` as a key to store messages.
When there are two messages with the same id but a different context, the latter one overwrites the former.
The fix is  to use `Catalog._get_key` as the key, same as for `_messages`.
This might be considered a breaking change, however the only documentation for `Catalog.obsolete` is [this](https://babel.pocoo.org/en/latest/api/messages/catalog.html#babel.messages.catalog.Catalog.update):
The docs never say anything about how the keys are computed, so I think it should be safe to make this change (and perhaps document it too?)

Fix the way obsolete messages are stored

---

babel/messages/catalog.py
babel/messages/frontend.py
babel/util.py

Since python 3.7, `dict` preserves insertion order. I think we can safely replace `OrderedDict` with `dict`.

Replace `OrderedDict` with just `dict`

---

scripts/download_import_cldr.py
tests/test_core.py
tests/test_date_intervals.py
tests/test_numbers.py
tests/test_units.py

[CLDR 46](https://cldr.unicode.org/downloads/cldr-46) is out now, let's upgrade.
Looking at the release notes, I don't think there's anything we need to update in babel, but another pair of eyes would be nice :)

Use CLDR 46

---

babel/dates.py
tests/test_dates.py

Closes #1090 
This uses `parse_pattern` internally when a custom format is used.

Allow specifying an explicit format in parse_date/parse_time

---

babel/messages/mofile.py

`Catalog.charset` is set to `utf-8` when no charset is provided (which is the case here) so the `if` check is redundant.

Simplify `read_mo` logic regarding `catalog.charset`

---

.github/workflows/ci.yml
.pre-commit-config.yaml
tests/test_support.py

Follows up on #1153 to use Ubuntu 24.04 for tests too, and bumps to macOS 14 from the [now-deprecated](https://github.com/actions/runner-images/issues/10721) macOS 12 runner.

Bump CI/tool versions

---

babel/messages/extract.py
tests/messages/test_frontend.py
tests/messages/utils.py

Otherwise, if I want to use a different method for one file AND use options, I can't do, for example:
```ini
[myextractor: path/file.py]
myoption = myvalue
[python: path/**.py]
```
The current code will match `path/file.py` to `myextractor`, but it'll use the empty options from `python`...

fix: check_and_call_extract_file uses the first matching method and options, instead of the first matching method and last matching options

---

babel/messages/pofile.py
babel/util.py
tests/messages/test_pofile.py

Closes #1078 
~~Depends on #1105 (To see only the changes in this PR, look at the last two commits)~~
Since #1105 wraps file names containing white space in special unicode markers, we look out for them when
wrapping comments.
The fix overrides the `_split` method of `TextWrapper` where we manually generate the indivisible chunks, taking into
account enclosed file names.
I test the the wrapping behavior with gettext 0.22.5 (which includes the enclosing logic) to make sure it's consistent

Prevent wrapping file locations containing white space

---

babel/dates.py
tests/test_dates.py

Support short and narrow formats for format_timedelta when using `add_direction`

---

babel/core.py
babel/dates.py
babel/lists.py
babel/messages/catalog.py
babel/messages/plurals.py
babel/messages/pofile.py
babel/numbers.py
babel/support.py
babel/units.py
tests/test_core.py
tests/test_lists.py
tests/test_numbers.py

This PR improves the handling of `None` as a `locale=` argument.
Namely:
* The error message `Locale.parse()` raises for falsy arguments is more descriptive.
* Explicitly passing in `None` for a public API means "use the default", not "crash on me".
* ⚠️ :point_right: This could change the behavior of user code that is not very well defined to begin with, that would have expected an exception to be raised for a `None` locale, but I hope that sort of code isn't very popular.
* If a default is not available (e.g. on Windows, or when environment variables are fubar'd), we'll still crash, but with a nicer error message than ever before.
Fixes #1156.
Closes #1158 (supersedes it).

Improve handling for `locale=None`

---

babel/localtime/_unix.py
tests/test_localtime.py

Fixes #990
Closes #1006 (supersedes it)
Closes #1035 (supersedes it)

Strip extra leading slashes in `/etc/localtime`

---

babel/messages/catalog.py

AFAICT, this is a noop and can be removed.

Remove redundant assignment in `Catalog.__setitem__`

---

babel/messages/catalog.py
tests/messages/test_catalog.py

Relevant issue: https://github.com/python-babel/babel/issues/333
Part 1 of adding support for checking f-string parameters. This simply adds a new property on the `Message` object analogous to `python_format` which sets the corresponding flag. In a followup PR I'm going to add a checker for the f-string format (reusing my implementation from https://github.com/python-babel/babel/pull/1168)
@akx (I can't ask for a review so I'm tagging you ;))

Add `Message.python_brace_format`

---

babel/core.py
babel/dates.py
babel/lists.py
babel/messages/extract.py
babel/messages/pofile.py
babel/numbers.py
babel/plural.py
babel/support.py
babel/units.py

[`typing.Literal`](https://docs.python.org/3/library/typing.html#typing.Literal) was added in 3.8. We can import it directly instead of relying on `typing_extensions`.
Edit: `TypedDict` as well
cc @akx

Import `Literal` from the typing module

---

babel/dates.py
tests/test_dates.py

Fix #1133.
I confirmed the added test cases for week-numbering are correct using PyICU library.

Fix dates formatting `Y`, `w` and `W` symbols for week-numbering

---

babel/messages/checkers.py
tests/messages/test_checkers.py

There a few bugs that I found in the `python_format` checker while working on the linter that I'd like to fix (e.g. one is that it does not validate `msgstr[N]` for `N >= 2`).
Though before I start fixing anything, I want to make sure we have the checker fully covered with tests as it would be pretty easy to accidentally introduce other bugs.
cc @akx

Increase test coverage of the `python_format` checker

---

pyproject.toml
setup.cfg

I think it's better to centralize the tool configs in one file rather than have it scattered across multiple files. What do you think?

Move pytest config to `pyproject.toml`

---

.github/workflows/ci.yml
tests/messages/test_setuptools_frontend.py

(The earlier fix accidentally slipped into `master` 🤦)

Mark PyPy CI flake as xfail

---

babel/messages/checkers.py
tests/messages/test_checkers.py

Previously, the format checker would only validate the first 2 plurals. If a locale had more than two plurals, those would not be checked. This PR fixes that.

Validate all plurals in python format checker

---

.github/workflows/ci.yml
.pre-commit-config.yaml

* The usual bumps of action versions (with https://github.com/akx/gha-tools)
* Switches the pre-commit step to a vendored version of https://github.com/akx/pre-commit-uv-action to save some cycles.
* Upgrades pre-commit's repos (Ruff 0.9.1 to 0.12.12), and pre-commit-hooks from 5 to 6.

Renovate CI & lint tools
